### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by kgilmer** [eddelbuettel/pkg-fonts-jetbrains-mono#1]
Hi @eddelbuettel, I just wanted to say thanks for providing this.  I was able to easily take your work and package the font in my PPA.  :smile: :fireworks:

**Comment by eddelbuettel** [comment]
Sure. My pleasure. 

But please don't file bogus issue tickets. This isn't a message board. You know where to find me if you want to quietly email thank you.  I'll delete this issue in a day or two unless I forget about it.
